---
title: "STA 404: Homework 3"
author: "Victoria Castel"
date: "`r Sys.Date()`"
output: 
  prettydoc::html_pretty:
    toc: true
    theme: cayman
    highlight: github
---
## Load packages and data
```{r}
## Load packages
library(tidyverse)
library(readxl)
library(lubridate)
```

```{r}
## Read data file: “Weekly_US_Crude_Oil.xlsx”
oil_data <- read_excel("Weekly_US_Crude_Oil.xlsx", skip=2) ## skip first 2 rows
glimpse(oil_data)
```

## Data cleaning
```{r, message=FALSE, warning=FALSE}
## Rename cols so they're easier to work with
oil_renamed <- oil_data %>%
  rename("year_month" = `...1`,
         "week1_dates" = `End Date...2`,
         "week1_values" = `Value...3`,
         "week2_dates" = `End Date...4`,
         "week2_values" = `Value...5`,
         "week3_dates" = `End Date...6`,
         "week3_values" = `Value...7`,
         "week4_dates" = `End Date...8`,
         "week4_values" = `Value...9`,
         "week5_dates" = `End Date...10`,
         "week5_values" = `Value...11`) %>%
  ## Mutate statement: change to a date variable 
  mutate(year_month = str_replace_all(year_month, "^\\s+", ""), ## remove leading white space
         year_month = as.Date(paste0(year_month, "-01"), format = "%Y-%b-%d")) ## add dummy day for formatting

## Split into 2 dfs
oil_values <- oil_renamed %>%
  select(year_month, week1_values, week2_values, week3_values, week4_values, week5_values)

oil_dates <- oil_renamed %>%
  select(year_month, week1_dates, week2_dates, week3_dates, week4_dates, week5_dates)

## Data cleaning for values
oil_values_clean <- oil_values %>%
  pivot_longer(cols = -c(year_month),
               names_to = "Name",
               values_to = "Value") %>%
  filter(Value != " ") %>%
  mutate(Value = str_replace_all(Value, "\\s+$", ""), ## remove trailing white space
         ## remove "," for all values
         Value = as.numeric(str_replace_all(Value, ",", ""))) %>%
  select(year_month, Value)

## Data cleaning for dates
oil_dates_clean <- oil_dates %>%
  pivot_longer(cols = -c(year_month),
               names_to = "Name",
               values_to = "month_day") %>%
  mutate(month_day = str_replace_all(month_day, "\\s+$", ""), ## remove trailing white space for all dates
         month_day = as.Date(month_day, "%m/%d")) %>% ## convert to date type
  select(year_month, month_day)

## Join dfs
oil_clean <- full_join(oil_values_clean, oil_dates_clean) %>%
  na.omit() %>% ## drop NA values 
  mutate(Year = year(year_month),   ## extract year, month, and day as seperate cols
         Month = month(month_day),
         Day = day(month_day),
         ## Create date variable from extracted values
         Date = as.Date(paste0(Year, "-", Month, "-", Day))) %>%
  select(Date, Value) ## only these vars
```


## Graphs

### Weekly US field production of crude oil
```{r}
## Mini data handling to get by month
oil_weekly <- oil_clean %>%
  mutate(year_week = paste(year(Date), week(Date), 1, sep="-")) %>%
  group_by(year_week) %>%
  mutate(weekly_avg = mean(Value))

## Commented code was used to calculate the total average
oil_clean %>%
  summarise(avg=mean(Value))
  

ggplot(oil_weekly) +
  geom_line(aes(x=Date, y=weekly_avg), color="#25771B") +
  theme_minimal() +
  scale_x_continuous(limits = c(as.Date("1980-01-01"), as.Date("2025-01-01") ),
                     breaks = c(as.Date("1980-01-01"), as.Date("1990-01-01"), as.Date("2000-01-01"), 
                                as.Date("2010-01-01"), as.Date("2020-01-01") ),
                     labels = c("1980", "1990", "2000", "2010", "2020"),
                     minor_breaks = NULL) +
  scale_y_continuous(limits = c(3500, 13500),
                     breaks = c(seq(from=3500, to=13500, by=2500)),
                     labels = c("3,500", "6,000", "8,500", "11,000", "13,500"),
                     minor_breaks = NULL) +
  labs(title = "Weekly US field production of crude oil",
       subtitle = "Thousand barrels per day",
       caption = "Source: US Energy Information Administration") +
  theme(text = element_text(family="serif"),
        plot.caption = element_text(family="mono", color="grey40"),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(size=11),
        axis.text.y = element_text(size=11)) +
  annotate("text", x=as.Date("2002-01-01"), y=8200, label="Averge procuction:\n7,273 thousand barrels per day", 
           family="serif", color="#9c3971", size=3.6) +
  annotate("segment", x=as.Date("1980-01-01"), xend=as.Date("2025-01-01"),
           y=7273.664, yend=7273.664, color="#bb4487")


```

### Monthly US field production of crude oil
```{r}
## Mini data handling to find monthly avg
oil_monthly <- oil_clean %>%
  mutate(year_month = ymd(paste(year(Date), month(Date), 01, sep="-"))) %>% 
  group_by(year_month) %>%
  mutate(monthly_avg = mean(Value)) 

## Graph
ggplot(data=oil_monthly) +
  geom_line(aes(x=year_month, y=monthly_avg), color="#7a1e85") +
  theme_minimal() +
  scale_x_continuous(limits = c(as.Date("1980-01-01"), as.Date("2025-01-01") ),
                     breaks = c(as.Date("1980-01-01"), as.Date("1990-01-01"), as.Date("2000-01-01"), 
                                as.Date("2010-01-01"), as.Date("2020-01-01") ),
                     labels = c("1980", "1990", "2000", "2010", "2020"),
                     minor_breaks = NULL) +
  scale_y_continuous(limits = c(3500, 13500),
                     breaks = c(seq(from=3500, to=13500, by=2500)),
                     labels = c("3,500", "6,000", "8,500", "11,000", "13,500"),
                     minor_breaks = NULL) +
  labs(title = "Monthly US field production of crude oil",
       subtitle = "Thousand barrels per day",
       caption = "Source: US Energy Information Administration") +
  theme(text = element_text(family="serif"),
        plot.caption = element_text(family="mono", color="grey40"),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(size=11),
        axis.text.y = element_text(size=11),
        panel.background = element_rect(fill = "#abeaa3"))
  
```

